apiVersion: apps/v1
kind: Deployment
metadata:
  name: splitdim
  labels:
    app: splitdim
spec:
  selector:
    matchLabels:
      app: splitdim
  template:
    metadata:
      labels:
        app: splitdim
    spec:
      terminationGracePeriodSeconds: 600
      containers:
        - name: splitdim
          image: localhost/splitdim:latest
          ports:
            - containerPort: 8080
          env:
            - name: KVSTORE_MODE
              value: kvstore
            - name: KVSTORE_ADDR
              value: "kvstore.default:8081"
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 2

---
apiVersion: v1
kind: Service
metadata:
  name: splitdim
  labels:
    app: splitdim
spec:
  type: LoadBalancer
  selector:
    app: splitdim
  ports:
    - name: http-port
      port: 80
      protocol: TCP
      targetPort: 8080
