apiVersion: v1
kind: Service
metadata:
  name: splitdim
  labels:
    app: splitdim
spec:
  selector:
    app: splitdim
  ports:
    - name: "http-splitdim"
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: splitdim
spec:
  gatewayClassName: istio
  listeners:
    - name: http-splitdim
      port: 80
      protocol: HTTP
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: splitdim
spec:
  parentRefs:
    - name: splitdim
  rules:
    - matches:
        - headers:
            - name: user
              value: test
      backendRefs:
        - name: splitdim-2
          port: 80
    - backendRefs:
        - name: splitdim
          port: 80
